import type {Metadata} from 'next';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='m-auto max-h-[100%] max-w-150 bg-white px-4 py-4 shadow-2xl'>
          <header className='h-4 text-xl font-bold'>
            <Link href={'/'}>📚 ONEBITE BOOKS</Link>
          </header>
          <main className='pt-2'>{children}</main>
          <footer className='py-25 text-gray-400'>제작 @kimminna</footer>
        </div>
      </body>
    </html>
  );
}
